### ISSUE TITLE
How to use pre-existing model?

### ISSUE THREAD

**Issue by cthoyt** [hasic-haris/one_step_retrosynth_ai#1]
Are the pre-trained models described in your paper available? If not, could you post them to a repository like Zenodo along with instructions on how to use them?

**Comment by hasic-haris** [comment]
Unfortunately, they are not available for usage in the current repository since it is assumed that everything can be easily done from scratch. However, I will try to construct appropriate checkpoints for the two best fingerprint models in the next week and make them available for usage with instructions. Until then, I'll let this issue be open. Thank you for your interest.

**Comment by queliyong** [comment]
Hi, 
I did not find the models in this repository.  Thank u very much.

**Comment by hasic-haris** [comment]
Hello and thank you for the interest in our research.

As I mentioned in my previous answer, the model checkpoints for this approach are not available since it is assumed that everything can be easily done from scratch.

However, given that the TensorFlow 1.x. library is deprecated by now, this approach and the model (PyTorch 1.x.) checkpoints will be included in a new repository outlining the continuation of the approach, which is currently under development. I will make sure to link this new repository in the README once it is finished. In the meantime, I will close this issue.
